# Description: Configuration file for the project
BASE:
  DATA:
    BATCH_SIZE: 4
    SCALE: false
  MODEL:
    HIDDEN_DIM: 256
    N_HIDDEN: 5
    TIMESTEPS: 10  # 1 for navigate to cluster, 1 for close range correction
    TIME_EMBEDDING: 5
    EPSILON: 0.001
    ACTIVATION: leaky_relu
    OUT_ACTIVATION: None
    lr: 0.00005
    NOISE: 1.0
    LOAD: False  #"epoch=9-step=140.ckpt"  TODO: load doesn't work
    USE_LABEL_FOR_DECODER: False
  LOSS:
    NOISE_L2: 1. #1.
    CLASS_BCE: 0.
    RECON_L2: 100.
  TRAINER:
    max_epochs: 2000
    log_every_n_steps: 100
    # overfit_batches: 0
    # CONTINUE_TRAINING: True

TRAIN:
  TRAINER:
    max_epochs: 2000


# hvad jeg er i tvivl om:
# er det for bredt: nej
# include outlook
# Include words: torque, momentum, gravity.
# 40 - 100 pages


BUILD:
  TRAINER:
    max_epochs: 1
    fast_dev_run: True
