# Description: Configuration file for the project
BASE:
  DATA:
    BATCH_SIZE: 128
    ROTAION: 0
    SCALE: .0
    TRANSLATE_X: 0.0
    TRANSLATE_Y: 0.0
    SHEAR: 0.0
    NORMALIZE_MEAN: 0.0
    NORMALIZE_STD: 1.0
    BOOL: false
    NO_NORMALIZE: False
  MODEL:
    ACTIVATION: leaky_relu
    OUT_ACTIVATION: sigmoid
    LEARNING_RATE: 0.0005
    LATENT_DIM: 8
    # MUL_KL_PER_EPOCH: 1
    LATENT_DROP_OUT_RATE: 0.0
    DROPOUT: 0.1
    UMAP_FREQ: 1  # if -1 disable
    RECON_FREQ: 1  # if -1 disable
    COV_FREQ: 50  # if -1 disable
  LOSS:
    RECONSTRUCTION_L2: 1.
    DIVERGENCE_KL: 0.000_0001

BUILD:
  DATA:
    BATCH_SIZE: 4
    SHUFFLE: false
  MODEL:
    ENABLE_UMAP: False
    verbose: true  
  TRAINER:
    max_epochs: 1
    log_every_n_steps: 40
    overfit_batches: 1
    check_val_every_n_epoch: 100
    enable_checkpointing: false
    # detect_anomaly: true
    # CONTINUE_TRAINING: False
    # resume_from_checkpoint: null
    fast_dev_run: False

TRAIN:
  TRAINER:
    max_epochs: 1000
    log_every_n_steps: 94
    # CONTINUE_TRAINING: False

OPTUNA:
  # vary: KL loss weight, latent dropout rate
  TRAINER:
    max_epochs: 5
    log_every_n_steps: 100
    fast_dev_run: False
  OPTIMIZE:
    n_trials: 3
    timeout: 240