# Description: Configuration file for the project
DIFFUSE:
  DATA:
    BATCH_SIZE: 512
    V: 4
    SCALE: True
  MODEL:
    LATENT_DIM: 16
    HIDDEN_DIM: 256
    N_HIDDEN: 12
    TIMESTEPS: 64  # 1 for navigate to cluster, 1 for close range correction
    TIME_EMBEDDING: 20
    EPSILON: 0.0001
    ACTIVATION: leaky_relu
    OUT_ACTIVATION: None
    LEARNING_RATE: 0.001
    NOISE: .3
    LOAD: False  #"epoch=9-step=140.ckpt"  TODO: load doesn't work
    USE_LABEL_FOR_DECODER: False
  LOSS:
    NOISE_L2: 1 #1.
    CLASS_BCE: 0.
    RECON_L2: 100.
  TRAINER:
    max_epochs: 200
    log_every_n_steps: 100
    # overfit_batches: 0
    # CONTINUE_TRAINING: False


# hvad jeg er i tvivl om:
# er det for bredt: nej
# include outlook
# Include words: torque, momentum, gravity.
# 40 - 100 pages