# Description: Configuration file for the project
BASE:
  DATA:
    BATCH_SIZE: 32
    ROTAION: 0
    SCALE: 0
    TRANSLATE_X: 0
    TRANSLATE_Y: 0
    SHEAR: 0
    NORMALIZE_MEAN: 0.1290
    NORMALIZE_STD: 0.3074
    BOOL: False
    NO_NORMALIZE: False
  MODEL:
    CLIPPED_REVERSE_DIFFUSION: true
    LEARNING_RATE: 0.002
    TIMESTEPS: 1000
    TIME_EMBEDDING_DIM: 32
    NOISE_SCHEDULE_METHOD: 'square'
    EPSILON: 0.0008
    BETA_START: 0.001
    BETA_END: 0.01
    BASE_DIM: 32

BUILD:
  DATA:
    BATCH_SIZE: 1
    SHUFFLE: false
  TRAINER:
    max_epochs: 600
    log_every_n_steps: 40
    overfit_batches: 1
    check_val_every_n_epoch: 100
    enable_checkpointing: false
    # detect_anomaly: true
    # CONTINUE_TRAINING: False
    fast_dev_run: true

TRAIN:
  MODEL:
    SAMPLE_EVERY: 1
  # DATA:
  #   MAX_SAMPLES: 4000
  TRAINER:
    max_epochs: 300
    log_every_n_steps: 20
    fast_dev_run: false

OPTUNA:
  MODEL:
    SAMPLE_EVERY: 9
  # DATA:
    # MAX_SAMPLES: 10000
  # vary: KL loss weight, latent dropout rate
  TRAINER:
    max_epochs: 10
    # log_every_n_steps: 50
    fast_dev_run: False
  OPTIMIZE:
    n_trials: 100
    timeout: 10800 # = 60*60*3

