# hidden_dim=512,
# nhidden=5,
# timesteps=1000,
# time_embedding_dim=12,
# target_embedding_dim=100,
# epsilon=0.0008,
# dp_rate=0.1,

# lr = 0.0001,
# verbose=False


TRAINER:
  fast_dev_run: false
  max_epochs: 1000
  enable_checkpointing: True
  log_every_n_steps: 100
  accelerator: mps

MODEL:
  hidden_dim: 256
  nhidden: 6
  timesteps: 2
  time_embedding_dim: 2
  target_embedding_dim: 32
  epsilon: 0.0008
  dp_rate: 0.05
  noise_multiplier: 1.0

  lr: 0.00005
  z_limit: 6.0


  verbose: false

DATA:
  batch_size: 4
  scale: false

  # shuffle: false

  
  tiny: 10000

FIT:
  load_checkpoint: false
