TRAIN:
  DATA:
    batch_size: 1024
    verbose: true
    tiny: false  # or false
    
  MODEL_BASE:
    verbose: false
    dropout: 0.10
    input_dim: 66
    latent_dim: 10
    learning_rate: 0.0002
    LOSS:
      DIVERGENCE_KL: 0.0000001
      MSE_L2: 1.

  MODEL_LINEAR:
    hidden_dims: [66, 128, 256]
    
  MODEL_GRAPH:
    c_in: 3
    c_hidden: 32
    c_out: 8
    n_layers: 6

  MODEL_CONV:
    dim_mults: [4, 2]

  TRAINER:
    accelerator: "mps"
    precision: "32-true"
    fast_dev_run: false
    max_epochs: 50

  FIT:
    load_checkpoint: false
