TRAIN:
  DATA:
    tiny: -1
  
  MODEL_1:
    nhead: 6
    ff_transformer: 1024
    nlayers_transformer: 5
    hidden_dim_linear: 1024
    activation: relu
    transformer_activation: relu

  MODEL_4:
    batch_norm: true
    latent_dim: 256
    nhead: 8
    nlayers_transformer: 5
    ff_transformer: 1024

  MODEL_5:

    latent_dim: 256
    nhead: 8
    num_layers: 5
    dim_feedforward: 1024
    dropout: 0.10

  MODEL_6:

    latent_dim: 256
    nhead: 8
    nlayers_transformer: 9
    transformer_activation: gelu
    dropout: 0.20

  MODEL_BASE:
    dropout: 0.10
    
    seq_len: 160


    learning_rate: 0.0000001
    clip_grad_norm: .02
    LOSS:
      DIVERGENCE_KL: 0.000003
      VELOCITY_L2: 0.0
      ROOT_L2: 0.0
      POSE0_L2: 1.0
      MOTION_L2: 1.0
      MOTIONRELATIVE_L2: 3.

  TRAINER:
    max_epochs: 1000
    enable_checkpointing: True
    log_every_n_steps: 10
    # overfit_batches: 1

  FIT:
    load_checkpoint: true
    
BUILD:
  DATA:
    batch_size: 2
    SHUFFLE: false
  MODEL:
    hidden_dim: 256
  TRAINER:
    #fast_dev_run: True
    overfit_batches: 1

BASE:
  MODEL_BASE:
    input_dim: 66
    hidden_dim_transformer: 256
    
    
    hidden_dim_linear: 256
    latent_dim: 1024

    # logging
    save_animations_freq: 1


  DATA:
    seq_len: 160
    batch_size: 16
    file_list_paths:
      _train: ../stranger_repos/HumanML3D/HumanML3D/train_cleaned.txt
      _val: ../stranger_repos/HumanML3D/HumanML3D/val_cleaned.txt
      _test: ../stranger_repos/HumanML3D/HumanML3D/test_cleaned.txt
    _motion_path: ../stranger_repos/HumanML3D/HumanML3D/new_joints
  TRAINER:
    accelerator: mps
    devices: 1
    precision: "32-true"
  