# hidden_dim=512,
# nhidden=5,
# timesteps=1000,
# time_embedding_dim=12,
# target_embedding_dim=100,
# epsilon=0.0008,
# dp_rate=0.1,

# lr = 0.0001,
# verbose=False


TRAINER:
  fast_dev_run: false
  max_epochs: 1000
  enable_checkpointing: True
  log_every_n_steps: 100
  accelerator: mps

MODEL:
  hidden_dim: 2048
  nhidden: 4
  timesteps: 10
  time_embedding_dim: 4
  target_embedding_dim: 512
  epsilon: 0.0008
  dp_rate: 0.15
  noise_multiplier: 3.0

  lr: 0.00001
  z_limit: 2.0


  verbose: false

DATA:
  batch_size: 64

  # shuffle: false

  
  # tiny: false

FIT:
  load_checkpoint: false
