# hidden_dim=512,
# nhidden=5,
# timesteps=1000,
# time_embedding_dim=12,
# target_embedding_dim=100,
# epsilon=0.0008,
# dp_rate=0.1,

# lr = 0.0001,
# verbose=False


TRAINER:
  fast_dev_run: false
  max_epochs: 1000
  enable_checkpointing: True
  log_every_n_steps: 100
  accelerator: mps

MODEL:
  hidden_dim: 128
  nhidden: 10
  timesteps: 4
  time_embedding_dim: 4
  target_embedding_dim: 16
  epsilon: 0.0008
  dp_rate: 0.15
  noise_multiplier: 1

  lr: 0.01
  z_limit: 10.0


  verbose: false

DATA:
  batch_size: 2
  scale: false

  # shuffle: false

  
  tiny: 70000

FIT:
  load_checkpoint: false
