MODEL:
  learning_rate: 0.000001
  latent_dim: 256
  nhead: 4
  num_layers: 3
  dim_feedforward: 1024
  dropout: 0.10
  transformer_activation: relu


  _save_animations: true
  load: false
  _checkpoint_path: latest
  activation: relu
  clip_grad_norm: 1.0
  batch_norm: true
  loss_weights:
    DIVERGENCE_KL: 0.000001
    # velocity_relative: 1.0
    # root: 0.0
    # pose0: 0.0
    # motion: 0.0
    MOTION_L2: 1.0
DATA:
  seq_len: 420
  batch_size: 32
  file_list_paths:
    _train: ../stranger_repos/HumanML3D/HumanML3D/train_cleaned.txt
    _val: ../stranger_repos/HumanML3D/HumanML3D/val_cleaned.txt
    _test: ../stranger_repos/HumanML3D/HumanML3D/test_cleaned.txt
  _motion_path: ../stranger_repos/HumanML3D/HumanML3D/new_joints
TRAINING:
  max_epochs: 1
  accelerator: mps
  devices: 1
  precision: "32-true"
  n_gpus: 1
  fast_dev_run: False
