# hidden_dim=512,
# nhidden=5,
# timesteps=1000,
# time_embedding_dim=12,
# target_embedding_dim=100,
# epsilon=0.0008,
# dp_rate=0.1,

# lr = 0.0001,
# verbose=False


TRAINER:
  fast_dev_run: false
  max_epochs: 1000
  enable_checkpointing: True
  log_every_n_steps: 100
  accelerator: mps

MODEL:
  hidden_dim: 1024
  nhidden: 4
  timesteps: 100
  time_embedding_dim: 32
  target_embedding_dim: 256
  epsilon: 0.0008
  dp_rate: 0.05
  noise_multiplier: .5

  lr: 0.00002
  z_limit: 3.0


  verbose: false

DATA:
  batch_size: 4
  scale: false

  # shuffle: false

  
  tiny: 4000

FIT:
  load_checkpoint: false
