TRAIN:
  DATA:
    tiny: true
  MODEL:
    hidden_dim: 256
  TRAINER:
    max_epochs: 1
    enable_checkpointing: True
    log_every_n_steps: 10
    

BUILD:
  MODEL:
    hidden_dim: 256
  TRAINER:
    fast_dev_run: True

BASE:
  MODEL:
    input_dim: 66
    nhead: 3
    hidden_dim_transformer: 256
    dropout: 0.10
    transformer_activation: relu
    hidden_dim: 256
    nlayers_transformer: 3

    seq_len: 420
    activation: relu
    hidden_dim_linear: 256
    latent_dim: 256


    learning_rate: 0.000001
    clip_grad_norm: 1.0
    save_animations_freq: 1

    load: false

    _checkpoint_path: latest
    
    
    LOSS:
      DIVERGENCE_KL: 0.00000001
      VELOCITY_L2: 1.0
      ROOT_L2: 0.0
      POSE0_L2: 0.0
      MOTION_L2: 0.0
      MOTIONRELATIVE_L2: 1.0
  DATA:
    seq_len: 420
    batch_size: 32
    file_list_paths:
      _train: ../stranger_repos/HumanML3D/HumanML3D/train_cleaned.txt
      _val: ../stranger_repos/HumanML3D/HumanML3D/val_cleaned.txt
      _test: ../stranger_repos/HumanML3D/HumanML3D/test_cleaned.txt
    _motion_path: ../stranger_repos/HumanML3D/HumanML3D/new_joints
  TRAINER:
    max_epochs: 10
    accelerator: mps
    devices: 1
    precision: "32-true"
  


