TRAIN:
  DATA:
    batch_size: 1024
    verbose: true
    
  MODEL_BASE:
    MODEL_TYPE: "graph"
    dropout: 0.10
    latent_dim: 48
    LEARNING_RATE: 1e-3

    LOSS:
      DIVERGENCE_KL_WEIGHT: 0.00000001
    KL_WEIGHT: 0.00000001

  MODEL_LINEAR:
    hidden_dim: 256
    

  MODEL_GRAPH:
    c_hidden: 64
    c_out: 32
    
    n_layers: 4



  TRAINER:
    
    __ACCERLATOR: "mps"
    __DEVICES: 1
    __PRECISION: "32-true"
    __N_GPUS: 1
    __N_WORKERS: 4
    __FAST_DEV_RUN: False
    load: false
