
BASE:
  MODEL:
    learning_rate: 0.000001
    latent_dim: 256
    nhead: 8
    nlayers_transformer: 5
    ff_transformer: 1024
    dropout: 0.10
    transformer_activation: relu
    _save_animations_freq: 1  # -1 to disable
    load: false
    _checkpoint_path: latest
    activation: leaky_relu
    clip_grad_norm: 1.0
    batch_norm: true
    LOSS:
      DIVERGENCE_KL: 0.0000000001
      ROOT_L2: 0.0
      MOTIONRELATIVE_L2: 0.0
      MOTION_L2: 1.
      VELOCITY_L2: 0.0

  DATA:
    seq_len: 420
    tiny: true
    batch_size: 64
    file_list_paths:
      _train: ../stranger_repos/HumanML3D/HumanML3D/train_cleaned.txt
      _val: ../stranger_repos/HumanML3D/HumanML3D/val_cleaned.txt
      _test: ../stranger_repos/HumanML3D/HumanML3D/test_cleaned.txt
    _motion_path: ../stranger_repos/HumanML3D/HumanML3D/new_joints

  TRAINER:
    max_epochs: 1
    accelerator: mps
    devices: 1
    precision: "32-true"
    # n_gpus: 1
    fast_dev_run: False


TRAIN:
  MODEL:
    hidden_dim: 256

BUILD:
  MODEL:
    hidden_dim: 256

  TRAINER:
    enable_checkpointing: false
    max_epochs: 1
    log_every_n_steps: 10
